name: Delete branch after PR merge
on: 
    pull_request:
        types:
            - closed
jobs:
    deleteMergedBranch:
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        
        runs-on: ubuntu-latest
        permissions: 
            contents: write
        
        steps:
            - name: Delete Branch
              env: 
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
              run: |
                
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                BRANCH_NAME = ${{ github.event.pull_request.head.ref }}
                if [[ BRANCH_NAME == 'main' || BRANCH_NAME == 'master' ]]; then
                  echo "Skipping deletion of protected branch: $BRANCH_NAME"
                  exit 0
                fi

                git push origin --delete "$BRANCH_NAME"

                  
        

